# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ayoub/Register_File/Register_File.srcs/sources_1/ip/Count_0/Count_0.xci
# IP: The module: 'Count_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ayoub/Register_File/Register_File.srcs/sources_1/ip/Count_0/Count_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Count_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/ayoub/Register_File/Register_File.srcs/sources_1/ip/Count_0/Count_0.xci
# IP: The module: 'Count_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ayoub/Register_File/Register_File.srcs/sources_1/ip/Count_0/Count_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Count_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
